services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    depends_on:
      - db
    volumes:
      - ./lms-api:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms_api
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./lms-api:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

volumes:
  db_data:

networks:
  app-network: